### ISSUE TITLE
When I run the example of pre-training on single GPU, An error occurred。

### ISSUE THREAD

**Issue by ZhaoxinRuc** [dbiir/UER-py#1]
Run as "python3 pretrain.py --dataset_path dataset.pt --vocab_path models/google_vocab.txt --output_model_path models/output_model.bin --encoder bert --target bert --gpu_ranks 0"
And then the results showed "TypeError: object of type 'NoneType' has no len()"

**Comment by Embedding** [comment]
I am sorry for this bug. We forget to pass gpu_ranks to the worker. We will fix it as soon as possible.
