### ISSUE TITLE
Could you provide the settings of the pretrained LstmEncoder models?

### ISSUE THREAD

**Issue by bb9696aa** [dbiir/UER-py#11]
The provided `feature_extractor.py` and `models/google_config.json` works perfect with BertEncoder pretrained models, but there is no settings providing for the LstmEncoder pretrained models.

Could you plz provide the settings for the pretrained `(Mixedlarge corpus & Amazon reviews)+LstmEncoder+(LmTarget & ClsTarget)` model? When I use the default `models/rnn_config.json` for this model, it errors like:
```
RuntimeError: Error(s) in loading state_dict for Model:
        Missing key(s) in state_dict: "target.output_layer.weight", "target.output_layer.bias".
        Unexpected key(s) in state_dict: "target.linear_1.weight", "target.linear_1.bias", "target.linear_2.weight", "target.linear_2.bias".
```

I'm not sure where the issue locates (probably the multiple targets I guess). More detail param settings of the pretrained models should be provided, since we don't know how to match the training params when inferencing.

Thank you in advance!

**Comment by Embedding** [comment]
Hi, thank you for this issue.
please try to set strict=False here.
```
load_state_dict(pretrained_model, strict=True)
```
The LSTM pre-trained model uses LM and CLS targets, which is different with BERT target.
We will change feature_extractor.py to make it more robust.

**Comment by bb9696aa** [comment]
> Hi, thank you for this issue.
> please try to set strict=False here.
> 
> ```
> load_state_dict(pretrained_model, strict=True)
> ```
> 
> The LSTM pre-trained model uses LM and CLS targets, which is different with BERT target.
> We will change feature_extractor.py to make it more robust.

It works, thanks a lot! 

Furthermore, if I want to get the average token embeddings to represent a sentence through the LSTM multiple targets pre-trained model, whether should I add the `[CLS]` token at the head of each sentence?

Unlike the `[CLS]` token using Bert Target, maybe the `[CLS]` token using `first LM targets then CLS targets` training strategy could get a good token embedding.

Or, maybe I just need to pick the last unpad token embedding to represent a sentence instead of the average strategy mentioned above? Since it's a LSTM-based model.

Really appreciate your patience and support, thank you!

**Comment by Embedding** [comment]
Hi, [CLS] is not suitable for encoders like RNN. Adding mean/max pooling is a good choice in practice.
I will add a pooling option in feature_extractor.py as soon as possible.

**Comment by bb9696aa** [comment]
> Hi, [CLS] is not suitable for encoders like RNN. Adding mean/max pooling is a good choice in practice.
> I will add a pooling option in feature_extractor.py as soon as possible.

Really helpful, thanks!
