### ISSUE TITLE
使用bert蒸馏到lstm时，载入模型报错

### ISSUE THREAD

**Issue by zhanlaoban** [dbiir/UER-py#115]
我想使用bert蒸馏到lstm，载入lstm_reviews_model.bin报错。

Traceback (most recent call last):
  File "run_classifier.py", line 345, in <module>
    main()
  File "run_classifier.py", line 275, in main
    load_or_initialize_parameters(args, model)
  File "run_classifier.py", line 82, in load_or_initialize_parameters
    model.load_state_dict(torch.load(args.pretrained_model_path), strict=False)
  File "/home/zhan/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Classifier:
	size mismatch for encoder.rnn.weight_ih_l0: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for encoder.rnn.weight_hh_l0: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for encoder.rnn.bias_ih_l0: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([2048]).
	size mismatch for encoder.rnn.bias_hh_l0: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([2048]).
	size mismatch for encoder.rnn.weight_ih_l1: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for encoder.rnn.weight_hh_l1: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for encoder.rnn.bias_ih_l1: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([2048]).
	size mismatch for encoder.rnn.bias_hh_l1: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([2048]).

**Comment by zhanlaoban** [comment]
bug fixed.

**Comment by ZhaoxinRuc** [comment]
看到您给出的报错显示应该是选择的预训练模型size与当前模型配置不一致，建议从这方面进行查错。
