### ISSUE TITLE
T5生成

### ISSUE THREAD

**Issue by wzy6642** [dbiir/UER-py#122]
请问如何利用预训练好的T5模型进行微调，从而做文本生成呢？谢谢~

**Comment by P01son6415** [comment]
我们正在完善T5的下游任务代码，请关注后续的更新。

**Comment by P01son6415** [comment]
我们已经更新t5下游任务代码，请参考 https://github.com/dbiir/UER-py/wiki/Finetune-the-tasks#fine-tuning-in-a-text2text-manner
