### ISSUE TITLE
新版本中pretrain中参数的设置问题

### ISSUE THREAD

**Issue by linwhitehat** [dbiir/UER-py#123]
您好，我下载的最新版的master项目，但是在pretrain中发现optimizer.options中的参数没有了，像学习率之类的要调整是需要自己添加吗？还是参数设置位置变了？

**Comment by Embedding** [comment]
大部分超参数统一到这个文件 https://github.com/dbiir/UER-py/blob/master/uer/opts.py
建议使用 `python3 pretrain.py -h` 这种方式查看超参数

**Comment by linwhitehat** [comment]
> 大部分超参数统一到这个文件 https://github.com/dbiir/UER-py/blob/master/uer/opts.py
> 建议使用 `python3 pretrain.py -h` 这种方式查看超参数

嗯嗯，好的我看到了，还不太熟悉所以以为都在pretrain里面设置，感谢
