### ISSUE TITLE
关于预训练过程中多卡与steps的关系

### ISSUE THREAD

**Issue by SuMeng123** [dbiir/UER-py#126]
您好，背景是我在预训练过程中，使用单机4张卡，batch_size=256。

我理解实际batch_size = 4\*256，那一个step是指跑了256条数据还是4*256条数据呢？因为我只是设置了total_step，我需要这个来估计自己一共跑了多少个epoch

**Comment by Embedding** [comment]
您好
预训练的实际batch size大小是 *--batch_size* 乘以 *--world_size*
根据您上面举的例子，一个step实际跑了4*256条数据

**Comment by SuMeng123** [comment]
> 您好
> 预训练的实际batch size大小是 _--batch_size_ 乘以 _--world_size_
> 根据您上面举的例子，一个step实际跑了4*256条数据

OK，感谢
