### ISSUE TITLE
关于CLUE C3

### ISSUE THREAD

**Issue by Tilendlesa** [dbiir/UER-py#130]
您好！请问预训练模型仓库中的albert_xlarge提示配置文件是albert_xlarge_config.json，但是models文件下没有这个文件。使用models/albert/xlarge_config.json配置会报错: RuntimeError: mat1 dim 1 must match mat2 dim 0。请问能否给予一下提示呢？
关于C3的竞赛解决方案提示使用bert_large,但是目前我使用11G三张显卡会报溢出错误，请问大概需要多少的硬件可以支持这种规模的训练呢。

**Comment by P01son6415** [comment]
可否给一下详细的报错信息？或者加我微信交流：poison6415

**Comment by LSQii** [comment]
> 您好！请问预训练模型仓库中的albert_xlarge提示配置文件是albert_xlarge_config.json，但是models文件下没有这个文件。使用models/albert/xlarge_config.json配置会报错: RuntimeError: mat1 dim 1 must match mat2 dim 0。请问能否给予一下提示呢？
> 关于C3的竞赛解决方案提示使用bert_large,但是目前我使用11G三张显卡会报溢出错误，请问大概需要多少的硬件可以支持这种规模的训练呢。

你好，我也遇到了同样的问题，直接改config倒是能跑，但是效果会差到35%accu左右，想问一下你这个问题解决了嘛
