### ISSUE TITLE
如何将下游任务改为篇章级别分类，而不是句子分类

### ISSUE THREAD

**Issue by linwhitehat** [dbiir/UER-py#131]
您好，我使用base bert预训练完成后，希望在下游任务做修订。
预训练任务中输入是单个句子，但是我的下游任务是多个句子的分类，我想修改下游输入的处理以及编码输出结果的处理，使输出结果能输入到最后的分类层，这部分在默认的run_classifier中应该如何修改？我查阅了一些资料，只需要获取cls的embedding结果，但是我不清楚这部分输出是在哪一块？能帮忙指明解释吗？

**Comment by Embedding** [comment]
*run_classifier.py* 支持篇章级别的分类。篇章级别的分类和句子级别的分类在处理上没有区别，只需要通过 *--seq_length* 指定长度就好
*run_classifier.py* 中的Classifier类里面说明了如何得到CLS位置的最后输出层向量

**Comment by linwhitehat** [comment]
> _run_classifier.py_ 支持篇章级别的分类。篇章级别的分类和句子级别的分类在处理上没有区别，只需要通过 _--seq_length_ 指定长度就好
> _run_classifier.py_ 中的Classifier类里面说明了如何得到CLS位置的最后输出层向量

谢谢答疑。有一些理解的疑惑再询问一下。
我看了run_classifier的代码，encode输出output就是cls的输出层向量吗？如果下游使用篇章级别分类，我的一个句子是128，那篇章选择seq_length为5个句子，设置640，这么处理的话是输入的1个样本就是一个篇章而不是一个句子，我这样理解正确吗？因为预训练好的模型是句子级别的，我想在输入样本为篇章时切割为句子，在encoder结果的cls向量再进行合并。

**Comment by Embedding** [comment]
> > _run_classifier.py_ 支持篇章级别的分类。篇章级别的分类和句子级别的分类在处理上没有区别，只需要通过 _--seq_length_ 指定长度就好
> > _run_classifier.py_ 中的Classifier类里面说明了如何得到CLS位置的最后输出层向量
> 
> 谢谢答疑。有一些理解的疑惑再询问一下。
> 我看了run_classifier的代码，encode输出output就是cls的输出层向量吗？如果下游使用篇章级别分类，我的一个句子是128，那篇章选择seq_length为5个句子，设置640，这么处理的话是输入的1个样本就是一个篇章而不是一个句子，我这样理解正确吗？因为预训练好的模型是句子级别的，我想在输入样本为篇章时切割为句子，在encoder结果的cls向量再进行合并。

我建议是把所有句子合并在一起，整体作为一个样本。这样操作简单并且模型能够对句子之间的信息进行建模
encode输出output输出后，需要经过pooling，得到固定维度的向量

**Comment by linwhitehat** [comment]
> > > _run_classifier.py_ 支持篇章级别的分类。篇章级别的分类和句子级别的分类在处理上没有区别，只需要通过 _--seq_length_ 指定长度就好
> > > _run_classifier.py_ 中的Classifier类里面说明了如何得到CLS位置的最后输出层向量
> > 
> > 
> > 谢谢答疑。有一些理解的疑惑再询问一下。
> > 我看了run_classifier的代码，encode输出output就是cls的输出层向量吗？如果下游使用篇章级别分类，我的一个句子是128，那篇章选择seq_length为5个句子，设置640，这么处理的话是输入的1个样本就是一个篇章而不是一个句子，我这样理解正确吗？因为预训练好的模型是句子级别的，我想在输入样本为篇章时切割为句子，在encoder结果的cls向量再进行合并。
> 
> 我建议是把所有句子合并在一起，整体作为一个样本。这样操作简单并且模型能够对句子之间的信息进行建模
> encode输出output输出后，需要经过pooling，得到固定维度的向量

好的，谢谢你的建议。我因为对bert的理解还不到位，所以想问一下，在第一个问题的回答中你指的**run_classifier.py 中的Classifier类里面说明了如何得到CLS位置的最后输出层向量**是什么意思？是下面图中的这部分分支的处理吗？如果我输入的是所有句子，最终输出的是只有1个CLS的输出是吗？因为我的文本内容没有具体的语义，加上预训练的时候是用单个句子进行训练的，所以才想试试把一个篇章的几个句子单独输入编码，将输出的每个CLS结果合并再进行分类。
![image](https://user-images.githubusercontent.com/20349381/115110602-d913a000-9fae-11eb-909a-4b84ef8d5e54.png)
