### ISSUE TITLE
请问seq_length与max_seq_length的区别是什么？

### ISSUE THREAD

**Issue by crazyforsaken** [dbiir/UER-py#132]
RT：请问seq_length与max_seq_length的区别是什么？
如果我想在预训练的时候使用128个token，但是在微调和下游任务时输入512个token，应当如何实现？请问这两个参数可以完成这个任务吗？

**Comment by Embedding** [comment]
*max_seq_length* 是指模型本身支持的最长的序列处理长度，是预训练模型权重本身的性质
而 *seq_length* 是指我们在训练的时候序列的长度，和当前处理的数据集有关
比如一般BERT模型最多支持512长度，那么它的 *max_seq_length* 是512，position embedding 的维度是 768*512（如果是BERT-base）。但是我们在增量预训练或者微调的时候，经常不需要这么长的长度。我们需要使用 *seq_length* 指定我们训练阶段需要的长度。*seq_length* 需要小于 *max_seq_length* 。

**Comment by crazyforsaken** [comment]
谢谢解答。
