### ISSUE TITLE
使用transformers库的AutoModel加载MixedCorpus+BertEncoder(large)+BertTarget出错

### ISSUE THREAD

**Issue by zyh3826** [dbiir/UER-py#133]
使用model = AutoModel.from_pretrained(mypath)加载出错。
config为：
`{
  "pooler_fc_size": 1024,
  "intermediate_size": 4096,
  "hidden_size": 1024,
  "hidden_act": "gelu",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "hidden_dropout_prob": 0.1}
`
词表为Google的107k。
出错信息为：
![image](https://user-images.githubusercontent.com/31238754/114680111-6650bd80-9d3f-11eb-8789-c04a3dabe19f.png)
似乎是词表的问题？是有其他的词表吗，还请解答，谢谢

**Comment by hhou435** [comment]
您好，请在config文件中手动设置`"vocab_size": 21128`，然后再重新测试一下

**Comment by zyh3826** [comment]
> 您好，请在config文件中手动设置`"vocab_size": 21128`，然后再重新测试一下

完美解决，谢谢
