### ISSUE TITLE
使用gpt2做豆瓣书评分类的时候除0报错

### ISSUE THREAD

**Issue by LeiShu-BNU** [dbiir/UER-py#135]
当我在使用GPT2蒸馏模型和豆瓣语料做预测的时候，输入如下命令：

> $ python3 run_classifier.py --pretrained_model_path models/gpt2/cluecorpussmall_gpt2_distil_seq1024_model.bin \
>  --vocab_path models/google_zh_vocab.txt --config_path models/gpt2/distil_config.json \
>  --train_path datasets/douban_book_review/train.tsv \
>  --dev_path datasets/douban_book_review/dev.tsv --test_path datasets/douban_book_review/test.tsv \
>  --learning_rate 3e-5 --batch_size 64 --epochs_num 2 \
>  --embedding word_pos_seg --remove_embedding_layernorm \
>  --encoder transformer --mask causal --layernorm_positioning pre

 运行时候的bash如下：

> Batch size:  64
> The number of training instances: 20000
> 2 GPUs are available. Let's use them.
> Start training.
> /home/xxx/miniconda3/envs/bert_serve/lib/python3.6/site-packages/torch/nn/parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
>   warnings.warn('Was asked to gather along dimension 0, but all '
> Epoch id: 1, Training steps: 100, Avg loss: 0.701
> Epoch id: 1, Training steps: 200, Avg loss: 0.695
> Epoch id: 1, Training steps: 300, Avg loss: 0.694
> Acc. (Correct/Total): 0.5188 (5188/10000) 
> Epoch id: 2, Training steps: 100, Avg loss: 0.784
> Epoch id: 2, Training steps: 200, Avg loss: 0.693
> Epoch id: 2, Training steps: 300, Avg loss: 0.693
> Acc. (Correct/Total): 0.5188 (5188/10000) 
> Test set evaluation.
> Confusion matrix:
> tensor([[5110, 4890],
>         [   0,    0]])
> Report precision, recall, and f1:
> Label 0: 0.511, 1.000, 0.676
> Traceback (most recent call last):
>   File "run_classifier.py", line 339, in <module>
>     main()
>   File "run_classifier.py", line 335, in main
>     evaluate(args, read_dataset(args, args.test_path), True)
>   File "run_classifier.py", line 225, in evaluate
>     p = confusion[i, i].item() / confusion[i, :].sum().item()
> ZeroDivisionError: division by zero
>

采用epochs=8的时候也是相同的问题。请问我是哪里弄错了，感谢回复！

**Comment by Embedding** [comment]
您好，对于GPT-2语言模型，需要使用（*--pooling mean*或者*--pooling max*或者*--pooling last*）
因为语言模型的遮罩因素，[CLS]位置（--pooling first）向量没有意义

**Comment by LeiShu-BNU** [comment]
> 您好，对于GPT-2语言模型，需要使用（_--pooling mean_或者*--pooling max_或者_--pooling last*）
> 因为语言模型的遮罩因素，[CLS]位置（--pooling first）向量没有意义

非常感谢！问题解决了。很棒的项目~
