### ISSUE TITLE
preprocess的输入文件需要什么样的格式

### ISSUE THREAD

**Issue by Msai25** [dbiir/UER-py#139]
我准备要做实体识别和关系抽取，用该项目进行预训练bert，以提高准确率。请问在预训练之前的数据处理阶段（preprocess），输入的预料需要什么样的格式呢？我看到书评是将一句话分成两行进行处理的，我的原数据是大量word文档内容，该处理成什么样的格式进行preprocess呢？而且这些文档具有标题目录表格等等内容，请问小标题、目录和表格这样的文本会影响预训练的效果吗？

**Comment by Embedding** [comment]
不同的目标任务需要的语料格式不一样，比如对于BERT（MLM+NSP targets），语料格式是：
```
doc1-sent1
doc1-sent2
doc1-sent3

doc2-sent1

doc3-sent1
doc3-sent2
```

对于LM和MLM目标任务，语料格式是：
```
doc1
doc2
doc3
```

更多的信息请参见[这里](https://github.com/dbiir/UER-py/wiki/%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B)

具体什么内容需要加到语料中，和下游任务有关系。可以做一些对比实验，比如先只用纯净的文本内容进行预训练，作为baseline

**Comment by Msai25** [comment]
感谢回复，谢谢
