### ISSUE TITLE
quickstart 报错

### ISSUE THREAD

**Issue by Yazhou-Liu** [dbiir/UER-py#14]
env: 

python3.6 pytorch 1.1

command:

 python pretrain.py 
--dataset_path dataset.pt
--vocab_path models/google_vocab.txt 
--pretrained_model_path models/google_model.bin                     
--output_model_path models/book_review_model.bin  
--world_size 8 --gpu_ranks 0 1 2 3 4 5 6 7                    
--total_steps 20000 \
--save_checkpoint_steps 5000 
--encoder bert --target bert

log:

Using distributed mode for training.
Vocabulary file line 344 has bad format token
Vocabulary Size:  21128
Bus error (core dumped)
/opt/conda/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 2 leaked semaphores to clean up at shutdown
  len(cache))

**Comment by Yazhou-Liu** [comment]
Use One GPU card can work。

python3 pretrain.py --dataset_path dataset.pt --vocab_path models/google_vocab.txt --pretrained_model_path models/google_model.bin                     --output_model_path models/book_review_model.bin  --world_size 1 --gpu_ranks 0   --total_steps 20000 --save_checkpoint_steps 5000 --encoder bert --target bert

**Comment by sl403** [comment]
I have the same problem. Has anyone solved this problem on multiple GPUs?
