### ISSUE TITLE
下游任务做交叉验证是否有集成的模块可调用？

### ISSUE THREAD

**Issue by linwhitehat** [dbiir/UER-py#142]
您好，我想询问下，在UER下的bert模型做下游分类任务时，是否有交叉验证的模块进行测试？有的话如何调用？

**Comment by P01son6415** [comment]
请参考 run_classifier_cv.py，以及 [SMP2020微博情绪分类技术评测](https://github.com/dbiir/UER-py/wiki/SMP2020微博情绪分类技术评测)

**Comment by linwhitehat** [comment]
> 请参考 run_classifier_cv.py，以及 [SMP2020微博情绪分类技术评测](https://github.com/dbiir/UER-py/wiki/SMP2020%E5%BE%AE%E5%8D%9A%E6%83%85%E7%BB%AA%E5%88%86%E7%B1%BB%E6%8A%80%E6%9C%AF%E8%AF%84%E6%B5%8B)

好的，我查看一下，谢谢
