### ISSUE TITLE
修改预训练的目标任务

### ISSUE THREAD

**Issue by linwhitehat** [dbiir/UER-py#144]
您好，我想修改预训练目标任务，即在bert或mlm的基础上增加其他任务的话应该怎么处理？
我想在masked的任务上做短语的mask，修改幅度类似将原先的预测单个token变为一组token这种，最终目标任务想在bert中做nsp任务、token和短语的mask任务，那么在uer/target下的mlm或bert应该需要修改什么内容？

**Comment by linwhitehat** [comment]
另外，我不太明白在nsp的任务上，是不是应该同时输入2个样本才行？这部分是需要修改现在uer数据输入的格式吗？

**Comment by Embedding** [comment]
做短语的mask，修改方式和whole word masking（WWM）类似。可以参考*uer/utils/data.py*文件中是如何引入WWM的
其余的应该不用变，仍然使用  *--target bert*

**Comment by linwhitehat** [comment]
> 做短语的mask，修改方式和whole word masking（WWM）类似。可以参考_uer/utils/data.py_文件中是如何引入WWM的
> 其余的应该不用变，仍然使用 _--target bert_

好的，我看一下，谢谢
