### ISSUE TITLE
关于在hugggingface的模型仓下没有基于词的RoBERTa这个模型的词典vocab.txt

### ISSUE THREAD

**Issue by zgj-gutou** [dbiir/UER-py#150]
你好，我没有在hugggingface的模型仓下找到基于词的RoBERTa这个模型（roberta-base-word-chinese-cluecorpussmall）的词典vocab.txt文件，请问这个模型不需要词典么？我按照参考程序试了下，tokenizer那里提示"Unable to load vocabulary from file. "。

**Comment by hhou435** [comment]
您好，基于词的模型使用了 sentencepiece进行分词，词典是模型仓库下的spiece.model文件，具体使用方法请参考模型Model card中的How to use

**Comment by zgj-gutou** [comment]
好的，ok了，刚才自己的程序有点问题。回复好快，给力给力。多谢多谢！
