### ISSUE TITLE
请教下，关于基于词的RoBERTa这个模型（roberta-base-word-chinese-cluecorpussmall）的编码问题

### ISSUE THREAD

**Issue by zgj-gutou** [dbiir/UER-py#151]
from transformers import AlbertTokenizer, BertModel
tokenizer = AlbertTokenizer.from_pretrained('./')
text = "用你喜欢的任何文本替换 我。"
encoded_input = tokenizer(text).input_ids
print("encoded_input:",encoded_input)
tokens = tokenizer.convert_ids_to_tokens(encoded_input)
print("tokens:",tokens)

（注意“我”这个字的前面有个空格）
结果打印出来是是：
encoded_input: [2, 17, 77, 26927, 915, 12386, 18373, 373, 16, 3]
tokens: ['[CLS]', '▁', '用', '你喜欢的', '任何', '文本', '替换', '▁我', '。', '[SEP]']

请问为什么开头处和空格处（“我”这个字的地方）会有'▁'这个token？

**Comment by hhou435** [comment]
您好，roberta-base-word-chinese-cluecorpussmall模型使用了sentencepiece进行分词，空格在sentencepiece中会被看作一个基本符号，具体细节在[google/sentencepiece](https://github.com/google/sentencepiece)的readme中有详细介绍
