### ISSUE TITLE
请问有测试过max_seq_len = 512时，单卡最大支持的batch_size是多少吗

### ISSUE THREAD

**Issue by yupeijei1997** [dbiir/UER-py#152]
您好，我在分类脚本中使用max_seq_len = 512进行测试，最大batch_size只能开到24，设32会显存溢出，请问这符合预期吗

**Comment by P01son6415** [comment]
显存占用情况取决于GPU设备、模型规模、seq_length和batch_size，可以根据自己的设备情况选择能够支持的模型和超参数进行实验
