### ISSUE TITLE
预训练卡在Worker is training ...这里，并且显存用的也很少

### ISSUE THREAD

**Issue by Shalearner** [dbiir/UER-py#156]

**Comment by Embedding** [comment]
您好，可以把语料的格式，preprocess.py、pretrain.py的命令，以及您的GPU机器的情况（比如几个GPU）发出来么？

**Comment by Shalearner** [comment]
GPU只有1个，3090，命令就是从github上复制过来的，就改了--world_size 1 --gpu_ranks 0&nbsp; \这一行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月10日(星期四) 下午5:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dbiir/UER-py] 预训练卡在Worker is training ...这里，并且显存用的也很少 (#156)





 
您好，可以把语料的格式，preprocess.py、pretrain.py的命令，以及您的GPU机器的情况（比如几个GPU）发出来么？

**Comment by Shalearner** [comment]
文件结构



以下是命令






然后就卡住不动了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dbiir/UER-py"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月10日(星期四) 下午5:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dbiir/UER-py] 预训练卡在Worker is training ...这里，并且显存用的也很少 (#156)





 
您好，可以把语料的格式，preprocess.py、pretrain.py的命令，以及您的GPU机器的情况（比如几个GPU）发出来么？

**Comment by Embedding** [comment]
之前修改项目mask.py出了问题
目前项目应该没有问题了
您可以再试试

**Comment by Shalearner** [comment]
现在跑例程没有问题了，但是换成自己的数据集的时候，用quickstart中的命令（修改了文件路劲），最后多线程的临时datase.pt文件不合并为最终的dataset.pt，就一直卡在那里

**Comment by P01son6415** [comment]
请删除缓存（临时文件），再运行一次
