### ISSUE TITLE
请问可以增加词典么？

### ISSUE THREAD

**Issue by macanv** [dbiir/UER-py#17]
你好，请问在进行预训练的时候,可以修改bert中文字典，增加一些oov的字进去进行训练么？

**Comment by zhezhaoa** [comment]
是的，但是如果您要更换词典的话，一定要修正模型，这样模型的embedding层和softmax层能和词典对应上。使用这个脚本dynamic_vocab_adapter.py即可。更具体的用法可参照readme以及这个链接https://zhuanlan.zhihu.com/p/74279985。在这个知乎链接中，我们展示了如果一个预训练模型的词典和标准的google中文词典不一样的话，我们应该如何对模型进行调整。

**Comment by macanv** [comment]
谢谢，如果这样work的话，可以解决BERT预训练中文模型中的OOV问题。
