### ISSUE TITLE
请问预训练模型仓库ZOO中的《其他机构中文预训练模型》中的albert和robert等模型是用哪个script文件convert的？谢谢！

### ISSUE THREAD

**Issue by MRC-Datasets** [dbiir/UER-py#184]
您好！
感谢提供UER-py
我在试用预训练模型ZOO的时候，在《其他机构中文预训练模型》中，从提供的腾讯云上，下载了ALBERT、Robert、BERT-wwm等模型，但是我发现这些模型不是表格最后一列提到的Google官方链接上的ckpt-best类型的文件，而是pytorch的bin文件。而我在UER的scripts文件夹中没有找到将albert、roberta、bert-wwm等模型转化为bin文件的脚本py文件。

请问这些表格第三列中的各类google模型是如何转化为腾讯云上您提供的bin文件模型呢？

谢谢！

**Comment by MRC-Datasets** [comment]
> 您好！
> 感谢提供UER-py
> 我在试用预训练模型ZOO的时候，在《其他机构中文预训练模型》中，从提供的腾讯云上，下载了ALBERT、Robert、BERT-wwm等模型，但是我发现这些模型不是表格最后一列提到的Google官方链接上的ckpt-best类型的文件，而是pytorch的bin文件。而我在UER的scripts文件夹中没有找到将albert、roberta、bert-wwm等模型转化为bin文件的脚本py文件。
> 
> 请问这些表格第三列中的各类google模型是如何转化为腾讯云上您提供的bin文件模型呢？
> 
> 谢谢！

**Comment by Embedding** [comment]
我们在这个项目提供的所有的预训练模型权重，都是UER项目可以直接加载的，因此不会存在TF格式的文件

我们新加了将UER和[Google TF格式的ALBERT](https://github.com/google-research/albert)互相转换的代码 
scripts/convert_albert_from_original_tf_to_uer.py 和 scripts/convert_albert_from_uer_to_original_tf.py

哈工大BERT-wwm项目提供了huggingface版本的pytorch格式预训练权重，我们通过 scripts/convert_bert_from_huggingface_to_uer.py 文件进行转换，得到UER格式的权重

**Comment by MRC-Datasets** [comment]
请问：
预训练模型ZOO中的《其他机构中文预训练模型》下的RoBERTa-wwm-ext模型，也是用如下文件：
scripts/convert_bert_from_huggingface_to_uer.py 文件进行转换，得到UER格式的权重的吗？

**Comment by MRC-Datasets** [comment]
您好！感谢回答，我做了一下转换，有些报错，恳请指导下：

首先，我下载了google的albert-base中文模型的V1版本，models文件夹中的包含的文件如下：
input_model.ckpt-best.meta
input_model.ckpt-best.index
model.ckpt-best.data-00000-of-00001
checkpoint
albert_config.json
vocab_chinese.txt

然后执行：python convert_albert_from_original_tf_to_uer.py

由于我安装的是Tensorflow2，报错：
module 'tensorflow_core.python.pywrap_tensorflow' has no attribute 'NewCheckpointReader'

因此我参考了以下的链接中的解决方法：
https://blog.csdn.net/u013085021/article/details/105471252

将：
from tensorflow.python import pywrap_tensorflow
reader =pywrap_tensorflow.NewCheckpointReader(args.input_model_path)
修改为：

from tensorflow.compat.v1.train import NewCheckpointReader
reader=NewCheckpointReader(args.input_model_path)

并将输入默认文件改为实际的albert的ckpt文件名称：
parser.add_argument("--input_model_path", type=str, default="models/model.ckpt-best.data-00000-of-00001",
                        help="Path of the input model.")


结果报错：
Traceback (most recent call last):
  File "convert_albert_from_original_tf_to_uer.py", line 86, in <module>
    main()
  File "convert_albert_from_original_tf_to_uer.py", line 26, in main
    reader = NewCheckpointReader(args.input_model_path)
  File "/data/home/scv2678/.conda/envs/py37/lib/python3.7/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 99, in NewCheckpointReader
    error_translator(e)
  File "/data/home/scv2678/.conda/envs/py37/lib/python3.7/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 44, in error_translator
    raise errors_impl.DataLossError(None, None, error_message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file models/model.ckpt-best.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?



于是，我卸载了TF2，重新安装了tensorflow1.15.4 ，将脚本文件还原，将硬盘上的albert的tf格式的model的名称从model.ckpt-best.data-00000-of-00001改为input_model.ckpt：

还是报错：
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file models/input_model.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

请问是那一步环节出问题了？非常感谢！

**Comment by hhou435** [comment]
您好，RoBERTa-wwm-ext是用convert_bert_from_huggingface_to_uer.py进行转换的，convert_bert_extractive_qa_from_huggingface_to_uer.py是用来转换BERT阅读理解模型的

**Comment by MRC-Datasets** [comment]
收到，谢谢
