### ISSUE TITLE
pretrain卡住不动

### ISSUE THREAD

**Issue by shilida** [dbiir/UER-py#196]
一直在这个页面....
Using distributed mode for training.
Worker 0 is training ... 
Worker 1 is training ...

**Comment by shilida** [comment]
显存使用率为0%

**Comment by hhou435** [comment]
麻烦提供一下运行命令

**Comment by shilida** [comment]
--dataset_path
corpora/dataset.pt
--vocab_path
model/robert/vocab.txt
--config_path
model/robert/bert-base-chinese/config.json
--pretrained_model_path
model/robert/bert-base-chinese/pytorch_model_uer.bin
--output_model_path
model/robert/bert-base-chinese/pytorch_model_law.bin
--world_size
2
--gpu_ranks
0
1
--total_steps
5000
--save_checkpoint_steps
1000
--batch_size
32
--embedding
word_pos_seg
--encoder
transformer
--target
bert

**Comment by hhou435** [comment]
preprocess的命令可以提供下吗 以及您使用的语料是bert格式吗

**Comment by shilida** [comment]
--corpus_path
corpora/law_bert.txt
--vocab_path
robert/vocab.txt
--dataset_path
corpora/dataset.pt
--processes_num
8
--target
bert

txt形式:一句一行

**Comment by hhou435** [comment]
一句一行的话用mlm任务，bert任务需要bert格式的语料，可以参考corpora里的例子*_bert.txt

**Comment by shilida** [comment]
![image](https://user-images.githubusercontent.com/39895844/130065326-7d240df4-ff8b-420f-9843-958d23b00130.png)
我是按照这个形式生成的，bert格式的语料是什么形式呢？我刚接触这个领域，谢谢大佬！！！

**Comment by hhou435** [comment]
可以参考corpora/CLUECorpusSmall_5000_lines_bert.txt这个文件

**Comment by shilida** [comment]
txt文件格式的问题，已解决，谢谢！
