### ISSUE TITLE
about vocab.txt

### ISSUE THREAD

**Issue by NoneWait** [dbiir/UER-py#2]
你好~请问其他模型比如人民日报的预训练模型的词表是 原有的google_vocab.txt吗？

**Comment by Embedding** [comment]
是的哈～因为我们的大部分预训练模型是基于字的。中文的字有限，OOV情况很少。所以不管什么语料，我们都统一用Google提供的包含21128个中文字符的词典。
后面我们会提供基于词的预训练模型。对于基于词的预训练模型，不同的语料会有不同的词典。

**Comment by NoneWait** [comment]
好的，谢谢~
