### ISSUE TITLE
tf-->uer

### ISSUE THREAD

**Issue by Smile-L-up** [dbiir/UER-py#204]
您好，非常感谢您的工作。我按照其他给的示例尝试转化，会报错。可以给一个tf-->uer转化的示例吗？另外tf版本是什么？

**Comment by P01son6415** [comment]
我们测试的tf版本是1.x

示例如下：
```python3 scripts/convert_bert_from_original_tf_to_uer.py --input_model_path models/input_model.ckpt --output_model_path models/pytorch_model.bin --layers_num 12```

如果遇到报错可以发出来我们看一下

**Comment by Smile-L-up** [comment]
感谢您这么快的回复，已经可以了。有两个注意点：一是模型文件后缀要改成 ".ckpt，"，二就是tf版本要匹配。
