### ISSUE TITLE
用自己的语料微调gpt2语言模型后进行文本生成任务，生成的文本为什么出现这么多[SEP]

### ISSUE THREAD

**Issue by yuzhang112** [dbiir/UER-py#205]
这个认识
[CLS]这个认识结果显然是非常符合理性的[SEP][SEP]当然[SEP][SEP]了[SEP][SEP]趣[SEP][SEP][SEP][SEP][SEP][SEP][SEP]了[SEP][SEP][SEP][SEP][SEP][SEP][SEP][SEP][SEP][SEP][SEP][SEP][SEP][SEP][SEP]

**Comment by P01son6415** [comment]
[SEP] 是终止符，可以截取第一个 [SEP] 之前的文本作为有效结果

**Comment by yuzhang112** [comment]
感谢回复，我觉得这应该和我语料有关
