### ISSUE TITLE
请问微云下载的模型如何转化为pytorch bert？

### ISSUE THREAD

**Issue by hitxujian** [dbiir/UER-py#21]
从微云下载的模型利用转换脚本转换为pytorch的时候报错：
   output_model["bert.pooler.dense.weight"] = input_model["target.nsp_linear_1.weight"]
KeyError: 'target.nsp_linear_1.weight'

**Comment by hitxujian** [comment]
比如这里下载的模型  https://share.weiyun.com/5JWVjSE
如何在huggingfaces使用？

**Comment by zhezhaoa** [comment]
`python3 scripts/convert_bert_from_uer_to_huggingface.py --input_model_path models/rmrb_model.bin --output_model_path models/rmrb_hug_model.bin`
在我这里没有报错，可能是您的文件下载不完整，或者使用了别的脚本？

**Comment by hitxujian** [comment]
不好意思，我下载的是 jdbinary_cls_model.bin 这个文件，这个bin好像是缺少东西的

**Comment by zhezhaoa** [comment]
这个不是标准的BERT模型，因为target使用的是分类（类似infersent），所以会在target部分报错
如果要转换这个模型，删掉文件scripts/convert_bert_from_uer_to_huggingface.py中target部分就好哈（42行以后）
