### ISSUE TITLE
mrc result is pool

### ISSUE THREAD

**Issue by hitxujian** [dbiir/UER-py#22]
the cmrc result is pool,have you ever tested the result, and if tested,what's you parametes? thanks

**Comment by zhezhaoa** [comment]
We have tested on CMRC2018 and the results on devset are normal (testset is not available).
Could you provide the log when you run run_mrc.py?
The usage of run_mrc.py is provided in readme.

**Comment by hitxujian** [comment]
thanks for answering,it's my fault,i haven't load pretrained model correctly,and now i am runing again,the loss seems correct.
