### ISSUE TITLE
finetune/run_ner.py evaluate函数内部的 if else好多没有对齐？

### ISSUE THREAD

**Issue by withchencheng** [dbiir/UER-py#225]
finetune/run_ner.py  [evaluate函数](https://github.com/dbiir/UER-py/blob/master/finetune/run_ner.py#L156)
里面有好几处的else有点看不懂啊。。else的正上方没有对齐的 if，但是跑起来居然也像是对的呢

这几个else：
第193行，204行，还有 214行 上面，插了一段for这也行吗

**Comment by P01son6415** [comment]
确实有点问题，可能是缩进有误，你有没有兴趣尝试优化一下这段代码？

**Comment by withchencheng** [comment]
正在尝试优化😄

**Comment by P01son6415** [comment]
我们再次确认了一下，这里其实用的是一个 for else 逻辑，所以原本的写法也是正确的
再次感谢你的贡献😊
