### ISSUE TITLE
NER的cluener2020 dataset可以放进去吗

### ISSUE THREAD

**Issue by railwayc** [dbiir/UER-py#226]
比如 cluener2020/label2id.json，想基于https://huggingface.co/uer/roberta-base-finetuned-cluener2020-chinese 建立新的分类做微调

**Comment by P01son6415** [comment]
可以参照MSRA-NER数据集格式，转换CLUENER后使用

**Comment by BestSongEver** [comment]
您提供的链接里（[数据集下载](https://github.com/dbiir/UER-py/wiki/Datasets)）有cluener2020的三个tsv文件，但是没有label2id.json文件。请问在哪里可以获取？非常感谢  
@ydli-ai @railwayc
