### ISSUE TITLE
pegasus finetune/run_text2text.py

### ISSUE THREAD

**Issue by Penguin-jpg** [dbiir/UER-py#227]
![image](https://user-images.githubusercontent.com/69071861/143664854-6d0e0d5b-0efd-4d16-87a0-611c7f0926a1.png)
按照图中这样设定，不论资料有几笔都总是只跑一两百个step就停很久，然后跑出Acc为0，想请问是有哪部分设定错误了吗？
（已经有将uer/utils/constants.py的special_tokens_map.json路径修改为pegasus用的）

**Comment by hhou435** [comment]
按图上展示的是因为您的训练集比较小，所以不到200个step训练集就跑完了，因此只打印了100个step的loss，停很久是在dev集上进行测试，acc为0的话可能是跟您的任务有关，如果不是分类任务可能需要换一个评价指标，或者把输出结果打印出来看看是否合理

**Comment by Penguin-jpg** [comment]
> 按图上展示的是因为您的训练集比较小，所以不到200个step训练集就跑完了，因此只打印了100个step的loss，停很久是在dev集上进行测试，acc为0的话可能是跟您的任务有关，如果不是分类任务可能需要换一个评价指标，或者把输出结果打印出来看看是否合理

您好，谢谢您的回覆，因为我在下游任务微调那边没找到关于文本摘要的训练方式，所以选了text2text，如果不是的话，想请问应该使用哪种呢？

**Comment by Penguin-jpg** [comment]
> 按图上展示的是因为您的训练集比较小，所以不到200个step训练集就跑完了，因此只打印了100个step的loss，停很久是在dev集上进行测试，acc为0的话可能是跟您的任务有关，如果不是分类任务可能需要换一个评价指标，或者把输出结果打印出来看看是否合理

我将输出结果印出来后确实是可以训练摘要的，我想如您所说确实是评价指标的问题，谢谢。
