### ISSUE TITLE
T5-Chinese generation method

### ISSUE THREAD

**Issue by Arvid-pku** [dbiir/UER-py#231]
Thank you for your contribution to T5-Chinese. And I have one question about it.
I usually use the Huggingface/Transformers' API to train or fine-tune the models and I find that you also upload your model to Huggingface website. But when I used their code (https://github.com/huggingface/transformers/blob/master/examples/pytorch/translation/run_translation.py) to fine-tune your T5 model, it failed to generate any text. Do I miss any difference between you and them? Could I use the same code to fine-tune all the models?
Looking forward to your reply.
Thanks!

**Comment by P01son6415** [comment]
In our T5 implementation, we use special tokens incompatible with huggingface. Please consider using [text2text script](https://github.com/dbiir/UER-py/blob/master/finetune/run_text2text.py) to deal with translation task. Wiki: https://github.com/dbiir/UER-py/wiki/Finetune-the-tasks#fine-tuning-in-a-text2text-manner

**Comment by Arvid-pku** [comment]
Yeah, I found it. Thank you for your reply.
