### ISSUE TITLE
请问dataset_path lyric_dataset.pt的格式是什么？

### ISSUE THREAD

**Issue by Ai-Jiajia** [dbiir/UER-py#232]
您好，不好意思我没有找到dataset_path lyric_dataset.pt文件，请问这个文件的格式是什么，是从lyric.txt转换而来吗？ 

```
python3 preprocess.py --corpus_path corpora/lyric.txt \
                      --vocab_path models/google_zh_vocab.txt \
                      --dataset_path lyric_dataset.pt --processes_num 32 \
                      --seq_length 512 --target lm
```

**Comment by YubingWang** [comment]
你好，我也有同样的问题，lyric.txt和lyric_dataset.pt这两个file我都没有找到，不知道你是怎么解决的呢？

**Comment by zhezhaoa** [comment]
这里给出了lyric语料的来源
https://huggingface.co/uer/gpt2-chinese-lyric

需要下载数据，整理成语言模型需要的数据格式（一行一个样本），得到 lyric.txt 
然后用preprocess进行预处理 lyric.txt -> lyric_dataset.pt
用pretrain加载 lyric_dataset.pt进行预训练

**Comment by zhezhaoa** [comment]
> 你好，我也有同样的问题，lyric.txt和lyric_dataset.pt这两个file我都没有找到，不知道你是怎么解决的呢？

这里给出了lyric语料的来源
https://huggingface.co/uer/gpt2-chinese-lyric

需要下载数据，整理成语言模型需要的数据格式（一行一个样本），得到 lyric.txt 
然后用preprocess进行预处理 lyric.txt -> lyric_dataset.pt
用pretrain加载 lyric_dataset.pt进行预训练

**Comment by YubingWang** [comment]
> 
非常谢谢，我已经下载好了里面的Chinese-Lyrics-Corpus，不过里面的歌词是一长句一行，短句中间又空格，然后分段落的时候里面有空行。所以我不太清楚一行一个样本应该怎么整理，是不管长短句和段落，每一个句子中间都有空格吗？
![1654727855(1)](https://user-images.githubusercontent.com/75820394/172729060-3f31d5f6-ddee-4f59-9afa-018298c8dfee.png)
