### ISSUE TITLE
I am confused about scripts/build_vocab.py

### ISSUE THREAD

**Issue by MardoPP** [dbiir/UER-py#234]
The function of scripts/build_vocab.py is to build vocabulary. However, scripts/build_vocab.py uses tokenizer, which requires vocabulary to tokenize the text. In my view, scripts/build_vocab.py should not be involved with the tokenizer.

**Comment by lx865712528** [comment]
Hi! We have removed the tokenizer in `scripts/build_vocab.py`.
Please see PR #237.
