### ISSUE TITLE
run_text2text.py ImportError: cannot import name 'Seq2seqTarget' from 'uer.targets' (/content/UER-py/uer/targets/__init__.py)

### ISSUE THREAD

**Issue by Penguin-jpg** [dbiir/UER-py#258]
当执行run_text2text.py时出现了以下的错误讯息，之前使用时没有发生过，请问哪部分的设定需要修改吗？
![image](https://user-images.githubusercontent.com/69071861/153803114-baa69a4b-752b-4fc3-a124-ee6d71ae0134.png)

**Comment by hhou435** [comment]
您好，我们最近对项目进行了进一步的模块化拆分，一些命令可能有所变化，建议您参考这里的最新命令https://github.com/dbiir/UER-py/wiki/%E4%B8%8B%E6%B8%B8%E4%BB%BB%E5%8A%A1%E5%BE%AE%E8%B0%83#text2text%E6%96%B9%E5%BC%8F%E5%BE%AE%E8%B0%83

**Comment by Penguin-jpg** [comment]
> 您好，我们最近对项目进行了进一步的模块化拆分，一些命令可能有所变化，建议您参考这里的最新命令https://github.com/dbiir/UER-py/wiki/%E4%B8%8B%E6%B8%B8%E4%BB%BB%E5%8A%A1%E5%BE%AE%E8%B0%83#text2text%E6%96%B9%E5%BC%8F%E5%BE%AE%E8%B0%83

了解，谢谢回覆。
