### ISSUE TITLE
Text2text: Some parameters of model configuration are ignored when fine-tuning or inference

### ISSUE THREAD

**Issue by yrchen92** [dbiir/UER-py#279]
When we load a Pretrained T5 model and a configuration file to fine-tune or make inference, some parameters (such as tie_weight and share_embedding) seem to be ignored.
Related files: finetune/run_text2text.py, inference/run_text2text_infer.py

**Comment by hhou435** [comment]
This issue has been fixed by https://github.com/dbiir/UER-py/commit/f83515fffa9310ade00871ff64a21f85986f9fd6
