### ISSUE TITLE
训练 bert_wiki_word_model.bin 的具体参数是什么?

### ISSUE THREAD

**Issue by 5118Python** [dbiir/UER-py#28]
大神，pretrain.py 训练 bert_wiki_word_model.bin 的参数望提供一下出来，也希望自己预训练一下

**Comment by zhezhaoa** [comment]
The details of bert_wiki_word_model.bin can be found in https://mp.weixin.qq.com/s/OBkEsjNBJaYws8UQbZ9B0A

**Comment by 5118Python** [comment]
感谢解答
