### ISSUE TITLE
preprocess处理占用太大内存

### ISSUE THREAD

**Issue by vegaviazhang** [dbiir/UER-py#282]
预处理文件如下： 7.4G
-rw-r--r-- 1 zhangw zhangw 7.4G Mar  2 20:53 /home/zhangw/i_dataset/uer/medical.txt
服务器内存：128G   48核
开了40个进程处理后，服务器卡爆重启了?

**Comment by Embedding** [comment]
可以发一下您的preprocess脚本么？以及可以确定一下您的语料格式是否是正确的哈

**Comment by Embedding** [comment]
https://github.com/dbiir/UER-py/wiki/预处理

这里文档提到，--processes_num 指定预处理进程的数量。多进程能缓解预处理的速度问题，但是更多的进程会消耗更多的内存。可以根据内存和CPU选择合适的进程数量。
并且如果使用BERT这样需要负采样的预训练模型，需要注意到这里：
--docs_buffer_size 指定单进程缓存文档数量。更大的数量会消耗更多的内存，可以根据内存选择合适的缓存文档数量。

**Comment by vegaviazhang** [comment]
--corpus_path
/home/zhangx/i_dataset/uer/medical.txt
--vocab_path
models/google_zh_vocab.txt
--dataset_path
medical_dataset.pt
--processes_num
40
--data_processor
bert

**Comment by vegaviazhang** [comment]
用的就是bert  QAQ

**Comment by vegaviazhang** [comment]
语料格式：单篇文章分句；不同文章之间空一行

**Comment by Embedding** [comment]
您好，建议减少 --processes_num （比如12） 和 --docs_buffer_size
