### ISSUE TITLE
bert_wiki_word_model.bin 可以用来做文本生成吗？

### ISSUE THREAD

**Issue by 5118Python** [dbiir/UER-py#29]
bert_wiki_word_model.bin 可以用来做文本生成吗？配置json文件能提供一下吗？

**Comment by zhezhaoa** [comment]
The config file of bert_wiki_word_model.bin is models/bert_base_config.json
bert_wiki_word_model.bin can not be used for generating. You need to load pre-trained GPT model (see Text generator section in readme)

**Comment by 5118Python** [comment]
感谢解答
