### ISSUE TITLE
The error of "list index out of range" appears on line 44 of inference/run_classifier_infer.py

### ISSUE THREAD

**Issue by yrchen92** [dbiir/UER-py#296]
inference/run_classifier_infer.py line 44: line = line.strip().split("\t")
In the dataset reading stage when making inference, if there are multiple columns of data ('text_a' and 'text_b') with the empty field, strip will remove the \r\n at the end and the \t between the fields. That will result in the the number of columns divided by \t becomes 1. When it calls text_a, text_b = line[columns["text_a"]], line[columns["text_b"]], there will be a list index out of range problem.

The implementation of this problem in the finetune phase (line 142 of finetune/run_classifier.py): line = line[:-1].split("\t")
It is also necessary to ensure that there is only one newline character at the end of each line. For example, it cannot be \r\n in Windows format. Otherwise there is a risk of leaving a newline character in the text of the last field.

I recommended that all relevant issues should be dealt with in a unified manner.

**Comment by haoyanliu** [comment]
Thanks.
We update the strip operation for line ends as rstrip("\r\n"), which applies for win/mac/linux.
FYI, https://stackoverflow.com/questions/26280747/stripping-r-n-from-a-line
