### ISSUE TITLE
利用官方BERT进行下游任务（多分类）微调时报错

### ISSUE THREAD

**Issue by Moximixi** [dbiir/UER-py#298]
想要利用bert模型进行六分类下游任务微调，但是报错
运行命令：
``` shell
CUDA_VISIBLE_DEVICES=0  python3 finetune/run_classifier.py --pretrained_model_path models/bert-base-chinese/pytorch_model.bin \
                                   --vocab_path models/bert-base-chinese/bert-base-chinese-vocab.txt \
                                   --train_path datasets/weibo/train.tsv \
                                   --dev_path datasets/weibo/dev.tsv \
                                   --test_path datasets/weibo/test.tsv \
                                   --output_model_path models/bert_weibo_classifier_model.bin \
                                   --epochs_num 10 --batch_size 32 \
                                   --embedding word_pos_seg --encoder transformer --mask fully_visible
```
 下载的bert模型来自谷歌官方
train.tsv:
![image](https://user-images.githubusercontent.com/32200567/161226764-513fb779-24f2-48cf-aab6-ae9760566b63.png)
dev.tsv:
![image](https://user-images.githubusercontent.com/32200567/161226818-4033f5f2-c6a0-4aed-a3aa-fc5fceee6bcd.png)
test.tsv:
![image](https://user-images.githubusercontent.com/32200567/161227357-de2912e4-b0ea-41f8-804c-dc036adfa475.png)

三者都是严格按照官方文档进行格式化处理

报错图片：
![image](https://user-images.githubusercontent.com/32200567/161226611-c67c094f-b2c5-4226-b30f-6df8601ceb90.png)

之前进行二分类时没有问题。请问进行多分类任务时，是不是需要对`run_classifier.py`文件进行更改？

**Comment by CSL-Dataset** [comment]
把label标签从0开始标试试？ 1-6 改为 0-5

**Comment by P01son6415** [comment]
把label标签从0开始标试试？ 1-6 改为 0-5

**Comment by Moximixi** [comment]
谢谢楼上大兄弟，可以运行了；但是不知道为什么
