### ISSUE TITLE
大佬，lstm的预训练模型，有tensorflow版本的吗

### ISSUE THREAD

**Issue by gxdalu-yaya** [dbiir/UER-py#3]
如题~

**Comment by ZhaoxinRuc** [comment]
不好意思，暂时还没有tensorflow版本的发自我的华为手机-------- 原始邮件 --------发件人： guoxiang <notifications@github.com>日期： 2019年6月25日周二 傍晚5:05收件人： dbiir/UER-py <UER-py@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [dbiir/UER-py] 大佬，lstm的预训练模型，有tensorflow版本的吗 (#3)如题~
