### ISSUE TITLE
请问运行generate.py时发生embedding错误是怎么解决？

### ISSUE THREAD

**Issue by 5118Python** [dbiir/UER-py#30]
![image](https://user-images.githubusercontent.com/14151451/67597692-5c7b7900-f79e-11e9-8098-c205e134f216.png)
AttributeError: 'Namespace' object has no attribute 'embedding'

**Comment by 5118Python** [comment]
![image](https://user-images.githubusercontent.com/14151451/67597831-a6645f00-f79e-11e9-9170-6af38f69ce10.png)
args参数中没有指定啊，例子中给的执行参数没有提到embedding，这个embedding怎么指定？
python3 scripts/generate.py 	
            --pretrained_model_path models/gpt_model.bin 
            --vocab_path models/google_vocab.txt 
            --input_path story_beginning.txt 
            --output_path story_full.txt 
            --config_path models/google_config.json 
            --encoder gpt --target lm --seq_length 128 --top_p 0.6

**Comment by 5118Python** [comment]
parser.add_argument("--embedding", choices=["bert", "word"], default="bert")

**Comment by zhezhaoa** [comment]
We have fixed the problem in scripts/generate.py
Thank you very much
