### ISSUE TITLE
deepspeed单机/多机显存占用一样问题

### ISSUE THREAD

**Issue by cxfzzj** [dbiir/UER-py#311]
使用UER-py自带的bert_3.9B_config.json测试大规模的预训练，发现一台服务器跑deepspeed时占用的内存和两台服务器跑deepspeed时占用的内存一样（每个GPU片子上）。本人对此比较疑惑，按说使用多台服务器跑deepspeed，显存（每块卡）占用不是更少了吗？为什么和一台的时候是一样的，如果不能（多台）减小显存，那增加服务器的意义又在哪儿呢？

**Comment by hhou435** [comment]
每张GPU占用的显存是会随着使用的gpu数增加减小的，可以参考这个回答https://github.com/microsoft/DeepSpeed/issues/1883
