### ISSUE TITLE
pegasus 训练的dataset是不是和原文章不相同啊？

### ISSUE THREAD

**Issue by CheaSim** [dbiir/UER-py#331]
https://github.com/dbiir/UER-py/blob/e5641ba845365b7cac724da6f444d3710776c992/uer/utils/dataset.py#L598
Pegasus 原论文是需要两种mask，一种mask token再复原，一种是根据ROUGE mask sentence，但这里实现貌似是随机采样句子来mask？

**Comment by hhou435** [comment]
原论文里是有两个训练任务 MLM和GSG，PEGASUS-LARGE是只用了GSG任务训练，所以我们这里也只用了GSG。关于GSG的几种实现，论文里是给了三种Random、Lead和Principal，我们这里是只复现了前两种。

**Comment by CheaSim** [comment]
ok了解了。
