### ISSUE TITLE
相同条件，每次输出的结果均不同

### ISSUE THREAD

**Issue by bobo0810** [dbiir/UER-py#336]
huggingface的官方示例，每运行一次的pooler_output值都不相同，请教大佬解答疑惑~
```python
from transformers import BertTokenizer, BertModel

tokenizer = BertTokenizer.from_pretrained("uer/chinese_roberta_L-2_H-128")
model = BertModel.from_pretrained("uer/chinese_roberta_L-2_H-128")
text = "用你喜欢的任何文本替换我。"
encoded_input = tokenizer(text, return_tensors="pt")
output = model(**encoded_input)
print()
```
第一次
![image](https://user-images.githubusercontent.com/26057879/183560174-8e0eb5de-b6e8-4276-b3bf-078b21208d9e.png)
第二次
![image](https://user-images.githubusercontent.com/26057879/183560257-5a12977f-ad3c-4ad1-bc84-6d255cac4864.png)
第三次
![image](https://user-images.githubusercontent.com/26057879/183560372-d55f793a-d290-4ca1-9f09-73b216898384.png)

**Comment by bobo0810** [comment]
打算将pooler_output当做128维文本特征，但为啥每次输出均不同让人费解。

**Comment by hhou435** [comment]
因为我们上传的是RoBERTa模型，是没有nsp这个任务的，因此也没有pooler的相关权重，这部分是随机初始化的

**Comment by bobo0810** [comment]
> 因为我们上传的是RoBERTa模型，是没有nsp这个任务的，因此也没有pooler的相关权重，这部分是随机初始化的

好的，谢谢~
