### ISSUE TITLE
How should I preprocess training data samples when I use HuggingFace Transformers T5?

### ISSUE THREAD

**Issue by ShaneTian** [dbiir/UER-py#338]
I want to fine-tune a T5 model for text-to-text task (e.g. translation task) using HuggingFace Transformers [uer/t5-base-chinese-cluecorpussmall](https://huggingface.co/uer/t5-base-chinese-cluecorpussmall)
How should I preprocess my training source and target sequences? I noticed that there were only MLM task in the T5 pre-training stage.
- `src = [cls_token, src_token_1, src_token_2, ..., sep_token], tgt = [cls_token, tgt_token_1, tgt_token_2, ..., sep_token]`
- `src = [cls_token, src_token_1, src_token_2, ..., extra0_token, sep_token], tgt = [cls_token, extra0_token, tgt_token_1, tgt_token_2, ..., sep_token]`

**Comment by hhou435** [comment]
Hello, I have not used Huggingface Transformers to fine-tune the t5 model we uploaded. The main difference between the T5 model we trained and the T5 model trained by huggingface is the use of different tokenizers. We still use Berttokenizer while Huggingface uses T5tokenizer. A fine-tuning example of T5 is also given in our project https://github.com/dbiir/UER-py/wiki/Finetune-the-tasks#fine-tuning-in-a-text2text-manner

**Comment by ShaneTian** [comment]
> The main difference between the T5 model we trained and the T5 model trained by huggingface is the use of different tokenizers.

Do you mean that [uer/t5-base-chinese-cluecorpussmall](https://huggingface.co/uer/t5-base-chinese-cluecorpussmall) is not trained by UER-py, but HuggingFace?

> We still use Berttokenizer while Huggingface uses T5tokenizer.

If I want to use [uer/t5-base-chinese-cluecorpussmall](https://huggingface.co/uer/t5-base-chinese-cluecorpussmall), which tokenizer should I use?
`BertTokenizer` is used in [HuggingFace model card](https://huggingface.co/uer/t5-base-chinese-cluecorpussmall#how-to-use).

> A fine-tuning example of T5 is also given in our project https://github.com/dbiir/UER-py/wiki/Finetune-the-tasks#fine-tuning-in-a-text2text-manner

If I want to use HuggingFace Transformers to fine-tune this model ([uer/t5-base-chinese-cluecorpussmall](https://huggingface.co/uer/t5-base-chinese-cluecorpussmall)), how should I prepare my input data?

**Comment by hhou435** [comment]
1.I mean the difference between these two models [uer/t5-base-chinese-cluecorpussmall](https://huggingface.co/uer/t5-base-chinese-cluecorpussmall) [t5-base](https://huggingface.co/t5-base) 
[uer/t5-base-chinese-cluecorpussmall](https://huggingface.co/uer/t5-base-chinese-cluecorpussmall)This model is trained by UER 
2.Use Berttokenizer
3.I have not tried to fine-tune the T5 model using HuggingFace Transformers' script , the processing format of the corpus during the pre-training is like src = [cls_token, src_token_1, src_token_2, ..., sep_token] tgt = [cls_token, extra0_token, tgt_token_1, tgt_token_2, ..., sep_token]

**Comment by ShaneTian** [comment]
Thanks again.

3. In pre-training, the data format is:
  ```
  src_seq = "北京是中国的extra0，它具有悠久的extra1。"
  tgt_seq = "extra0首都extra1历史"
  src = [cls_token, src_token_1, ..., extra0_token, src_token_x, ..., extra1_token, sep_token]
  tgt = [cls_token, extra0_token, tgt_token_1, ..., extra1_token, tgt_token_x, ..., sep_token]
  ```
  Right?

  If I want to fine-tune a text-to-text generation task, like:
  ```
  src_seq = "北京是中国的首都，"
  tgt_seq = "它具有悠久的历史。"
  ```
  In your opinion, should I process my data format as:
  ```
  src = [cls_token, src_token_1, ..., src_token_n, sep_token]
  tgt = [cls_token, tgt_token_1, ..., tgt_token_n, sep_token]
  ```
  or:
  ```
  src = [cls_token, src_token_1, ..., src_token_n, extra0_token, sep_token]
  tgt = [cls_token, extra0_token, tgt_token_1, ..., tgt_token_n, sep_token]
  ```
  Which is better?

**Comment by hhou435** [comment]
The first format is used in our project https://github.com/dbiir/UER-py/blob/master/finetune/run_text2text.py#L77

**Comment by ShaneTian** [comment]
Thanks
