### ISSUE TITLE
使用第三方预训练模型的参数设置问题

### ISSUE THREAD

**Issue by kxy-cheng** [dbiir/UER-py#340]
您好，我在Modelzoo提供的腾讯云链接中下载了HFL的chinese-roberta-wwm-ext-pytorch.bin，请问在执行run_classifier.py时parameter中--spm_model_path应该如何设置？

**Comment by ydli-ai** [comment]
你好，chinese-roberta-wwm-ext-pytorch 不需要填spm_model_path
