### ISSUE TITLE
Could you please provide more details about the word-based bert?

### ISSUE THREAD

**Issue by zhou1323** [dbiir/UER-py#35]
Hi!

Now I'm faced with a task that I got a sentence and a word **XXX**. In this sentence, I need to find the specific word which is most similar to the word **XXX**.

I notice that you provide a word-based bert model which I believe is suitable for my task. But I don't understand how it works. Is it trained on Chinese **words** directly? How does it process the OOV words? Can we add more words to the vocabulary?

I would appreciate it if you could provide more information about this bert model.

**Comment by Embedding** [comment]
Thank you for your attention
We trained word-based BERT upon wikizh and retained 80 thousands words according to frequency. The pre-trained model and vocabulary are publicly available (see Chinese model zoo section).
All low-frequency words are mapped o [UNK]. You can change the model according to your vocabulary by using dynamic_vocab_adapter.py (see scripts section).
You have multiple choices to find similar words, including the use of cloze_test.py ,  topn_words_indep.py , and topn_words_dep.py . We hope the instructions in scripts section are really helpful to you.

**Comment by zhou1323** [comment]
Thank you for your reply! I'll read the scripts more carefully.
