### ISSUE TITLE
Can't load Reviews+LstmEncoder+LmTarget pretrain model

### ISSUE THREAD

**Issue by loserdog-err** [dbiir/UER-py#36]
Hi.
After i run  `python pretrain.py --dataset_path  dataset.pt --vocab_path models/google_zh_vocab.txt --output_model_path models/model.bin --gpu_ranks 0 --total_steps 20000 --save_checkpoint_steps 5000 --encoder lstm --target lm --learning_rate 1e-3 --pretrained_model_path reviews_lstm_lm_model.bin --config_path models/rnn_config.json --batch_size 16 `
it show  following error.
![image](https://user-images.githubusercontent.com/13502799/70851496-f0c9a880-1ed0-11ea-9954-5caad239ad29.png)
Can you tell me where I made a mistake,thx~

**Comment by zhezhaoa** [comment]
We are sorry for this mistake.
Set hidden_size in models/rnn_config.json to 512 will fix this problem.

**Comment by loserdog-err** [comment]
> We are sorry for this mistake.
> Set hidden_size in models/rnn_config.json to 512 will fix this problem.

Ok,it solve my problem.
thx~
