### ISSUE TITLE
Can we have models of the model zoo in pytorch-pretrained-bert format, or maybe a conversion script?

### ISSUE THREAD

**Issue by Morizeyao** [dbiir/UER-py#5]
首先十分感谢诸位的努力，这项工作很有意义。
我在尝试将你们的模型用于其他任务的过程中发现你们的Bert实现与pytorch-pretrained-bert不同，导致模型的变量名不同，无法直接导入。
请问你们这有对应的转换代码方案吗？

**Comment by Morizeyao** [comment]
我尝试写了一个转换代码，发现你们的segment_id有三个，pytorch-pretrained-bert的实现里，token_type_id有两个，这里发生了冲突。正在研究解决方案，不知道你们遇到了这个问题吗？

**Comment by Morizeyao** [comment]
Never mind, I solved the problem.

**Comment by Embedding** [comment]
Hi, we will release the conversion script to huggingface as soon as possible.
The dimension of our segment_id is [3, 768].
0 represents PAD; 1 represents the first sentence; 2 represents the second sentence.
Other weigths are the same with huggingface's pretrained model.

**Comment by Morizeyao** [comment]
Yeah I figured it out and finished the conversion along with the script.
经过检查，你们的模型里segment_id的第一行参数全为0，这一行也许是没有意义的。模型因此（可能也有别的原因）比hugging face的实现大出了约60MB，这里有优化空间。

**Comment by Embedding** [comment]
Thanks for your advice. We will check that later.
The conversion script convert_bert_from_uer_to_huggingface.py has been uploaded to scripts folder.
