### ISSUE TITLE
请问一下GPT的config在哪里？

### ISSUE THREAD

**Issue by zhouyang412** [dbiir/UER-py#73]
在models文件夹里没有找到。词表也是。

**Comment by Embedding** [comment]
您好哈
GPT GPT-2 BERT RoBERTa等模型共享配置文件，都是基于`models/bert_xxx_config.json`
目前基于字的所有中文预训练模型，都是基于Google原始的中文词典 `models/google_zh_vocab.txt`
可以参考instructions中GPT和GPT-2的的运行示例

**Comment by zhouyang412** [comment]
> 您好哈
> GPT GPT-2 BERT RoBERTa等模型共享配置文件，都是基于`models/bert_xxx_config.json`
> 目前基于字的所有中文预训练模型，都是基于Google原始的中文词典 `models/google_zh_vocab.txt`
> 可以参考instructions中GPT和GPT-2的的运行示例

好的，可是没我找到GPT的运行示例。。。

**Comment by P01son6415** [comment]
> > 您好哈
> > GPT GPT-2 BERT RoBERTa等模型共享配置文件，都是基于`models/bert_xxx_config.json`
> > 目前基于字的所有中文预训练模型，都是基于Google原始的中文词典 `models/google_zh_vocab.txt`
> > 可以参考instructions中GPT和GPT-2的的运行示例
> 
> 好的，可是没我找到GPT的运行示例。。。

在 wiki -> Instructions 中：
https://github.com/dbiir/UER-py/wiki/Instructions#gpt

**Comment by zhouyang412** [comment]
> > > 您好哈
> > > GPT GPT-2 BERT RoBERTa等模型共享配置文件，都是基于`models/bert_xxx_config.json`
> > > 目前基于字的所有中文预训练模型，都是基于Google原始的中文词典 `models/google_zh_vocab.txt`
> > > 可以参考instructions中GPT和GPT-2的的运行示例
> > 
> > 
> > 好的，可是没我找到GPT的运行示例。。。
> 
> 在 wiki -> Instructions 中：
> https://github.com/dbiir/UER-py/wiki/Instructions#gpt

万分感谢
