### ISSUE TITLE
gpt文本生成时embeddingsize mismatch

### ISSUE THREAD

**Issue by Tia-Cheung** [dbiir/UER-py#76]
参照instructions里gpt文本生成的方法复现时，遇到了`size mismatch for embedding.position_embedding.weight: copying a param with shape torch.Size([512, 768]) from checkpoint, the shape in current model is torch.Size([1024, 768])`的报错

训练模型
`preprocess.py 
--corpus_path corpora/book_review.txt --vocab_path models/google_zh_vocab.txt 
--dataset_path dataset.pt --processes_num 8 --target lm`

`pretrain.py  
--dataset_path dataset.pt --vocab_path models/google_zh_vocab.txt --output_model_path models/output_model.bin 
--config_path models/bert_base_config.json --learning_rate 1e-4 --gpu_ranks 0 --encoder gpt --target lm `

生成文本
`scripts/generate.py 
--pretrained_model_path models/output_model.bin-100000 --vocab_path models/google_zh_vocab.txt --input_path story_beginning.txt --output_path story_full.txt --config_path models/bert_base_config.json --encoder gpt --target lm`

配置文件都是没有改过的，想问下是否知道问题出在哪里？
谢谢

**Comment by P01son6415** [comment]
请在 generate.py 增加 --embedding bert 参数，这个问题是因为您训练的模型是gpt，generate.py 默认是用gpt2，embedding部分不同
