### ISSUE TITLE
请问UER是否可以应用到多标签分类任务上呢

### ISSUE THREAD

**Issue by wangchichi1999** [dbiir/UER-py#79]
nlp小白前来求助qaq

**Comment by P01son6415** [comment]
可以，datasets中的 smp2020-ewect 就是多标签分类任务

**Comment by wangchichi1999** [comment]
感谢回复！如果应用到英文任务上，除了更换model文件夹里选择的配置，模型，和词表；更换数据集之外，其他还需要改动咩？

**Comment by P01son6415** [comment]
不需要，如果用了BPE配置一下spm_model_path就行

**Comment by ShadowTeamCN** [comment]
> smp2020-ewect

smp2020-ewect 是多分类任务而不是多标签分类任务吧？二者的概念是不同的

**Comment by lizhipengpeng** [comment]
> > smp2020-ewect
> 
> smp2020-ewect 是多分类任务而不是多标签分类任务吧？二者的概念是不同的

多标签分类任务lable应该是1,0,1,0这样的，而多分类任务label就是一个数3或7 这样的 ，我的理解对吗？
那UER是不是目前只有对多分类任务处理的代码但是没有对多标签分类任务对应的代码呢？
