### ISSUE TITLE
Albert 模型报错

### ISSUE THREAD

**Issue by watermelon-lee** [dbiir/UER-py#82]
尝试了 Albert base/large等，均有类似错误：
RuntimeError: size mismatch, m1: [5504 x 128], m2: [1024 x 1024] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:283]

执行脚本命令如下：
CUDA_VISIBLE_DEVICES=2,3,4 python run_classifier_cv.py --pretrained_model_path models/google_zh_albert_large_model.bin \
                            --vocab_path models/google_zh_vocab.txt --output_model_path models/model-albert-large.bin \
                            --config_path models/albert_large_config.json \
                            --train_path xxx   train_features_path xxx/albert_large.npy \
                            --folds_num 5 --epochs_num 3  --batch_size 128 --encoder bert --seq_length 128

在readme中并没有见到关于albert使用的教程，望回答～

**Comment by Embedding** [comment]
Readme中的Instructions下有一个链接，可以转到包含更多细节的页面 https://github.com/dbiir/UER-py/wiki/Instructions 这里有使用ALBERT进行微调的方式
使用ALBERT进行微调需要加上选项 --factorized_embedding_parameterization --parameter_sharing

**Comment by watermelon-lee** [comment]
谢谢～
