### ISSUE TITLE
[BUG] Convert Bert from Huggingface to Uer 

### ISSUE THREAD

**Issue by iseesaw** [dbiir/UER-py#83]
`convert_bert_from_huggingface_to_uer.py` 中 `input_model` 的 `LayerNorm` 参数不是 `weight` 和 `bias`，应该也是 `gamma` 和 `beta`

https://github.com/dbiir/UER-py/blob/93a95c01168f6fc84d50008daa49854a95c62ab5/scripts/convert_bert_from_huggingface_to_uer.py#L24-L25

![image](https://user-images.githubusercontent.com/31267864/101429727-9544c600-393e-11eb-88bb-45265c6f400d.png)

**Comment by hhou435** [comment]
您好，使用最新版本的Transformers保存的模型中，LayerNorm的参数已经修改为了weight和bias
您下载的模型如果是使用旧版Transformers保存的，LayerNorm 参数可能仍然是gamma和beta，可以修改对应的参数进行使用。

**Comment by iseesaw** [comment]
嗯嗯，的确下载的是早期版本，谢谢~~
