### ISSUE TITLE
中文预处理数据为空

### ISSUE THREAD

**Issue by iseesaw** [dbiir/UER-py#84]
你好，我在中文数据上进行 Bert 的预处理，请问得到的数据为空会是什么原因呢？

![image](https://user-images.githubusercontent.com/31267864/101498070-a3c6c800-39a6-11eb-9139-72e05d826393.png)

**Comment by zhezhaoa** [comment]
您好
我看您选的是`--target bert`
因此必须要用BERT格式的语料，参照`corpora/book_review_bert.txt`

**Comment by iseesaw** [comment]
哦哦， 好的，谢谢！

开始没注意BERT语料格式，但是英文的却预处理成功了，而且预训练也有一定的效果呢 🤦‍♀️ 这回事什么原因呢。。

**Comment by P01son6415** [comment]
> 哦哦， 好的，谢谢！
> 
> 开始没注意BERT语料格式，但是英文的却预处理成功了，而且预训练也有一定的效果呢 🤦‍♀️ 这回事什么原因呢。。

错误的配置有时也能因为各种原因正常运行，但我们这么设计程序并不是为了它能跑起来，而是因为这样做是对的。具体的原因还请参考UER预处理相关逻辑的源码，以及BERT／RoBERTa论文原文了解。
