### ISSUE TITLE
run_c3.py报错：KeyError: 'BertEmbedding'

### ISSUE THREAD

**Issue by Judenpech** [dbiir/UER-py#90]
Traceback (most recent call last):
  File "UER-py-master/run_c3.py", line 249, in <module>
    main()
  File "UER-py-master/run_c3.py", line 180, in main
    model = MultipleChoice(args)
  File "UER-py-master/run_c3.py", line 24, in __init__
    self.embedding = globals()[args.embedding.capitalize() + "Embedding"](args, len(args.tokenizer.vocab))
KeyError: 'BertEmbedding'

**Comment by zhezhaoa** [comment]
为了更好的可扩展性和可读性，我们把BertEmbedding改成了WordPosSegEmbedding
可以参考instruction和Competition solutions中C3相关的命令
python3 run_c3.py --pretrained_model_path models/google_zh_model.bin --vocab_path models/google_zh_vocab.txt \
                  --train_path datasets/c3/train.json --dev_path datasets/c3/dev.json \
                  --epochs_num 8 --batch_size 16 --seq_length 512 --max_choices_num 4 \
                  --embedding word_pos_seg --encoder transformer --mask fully_visible

**Comment by Judenpech** [comment]
1. 参数choice存在限制：run_c3.py: error: argument --embedding: invalid choice: 'word_pos_seg' (choose from 'bert', 'word')
2. 删除choice限制后，显示无mask参数：run_c3.py: error: unrecognized arguments: --mask fully_visible
3. 添加mask参数后，报错：
Traceback (most recent call last):
  File "UER-py-master/run_c3.py", line 250, in <module>
    main()
  File "UER-py-master/run_c3.py", line 181, in main
    model = MultipleChoice(args)
  File "UER-py-master/run_c3.py", line 24, in __init__
    self.embedding = globals()[args.embedding.capitalize() + "Embedding"](args, len(args.tokenizer.vocab))
KeyError: 'Word_pos_segEmbedding'

**Comment by Judenpech** [comment]
> 为了更好的可扩展性和可读性，我们把BertEmbedding改成了WordPosSegEmbedding
> 可以参考instruction和Competition solutions中C3相关的命令
> 
> ```
> python3 run_c3.py --pretrained_model_path models/google_zh_model.bin --vocab_path models/google_zh_vocab.txt \
>                   --train_path datasets/c3/train.json --dev_path datasets/c3/dev.json \
>                   --epochs_num 8 --batch_size 16 --seq_length 512 --max_choices_num 4 \
>                   --embedding word_pos_seg --encoder transformer --mask fully_visible
> 
> python3 inference/run_c3_infer.py --load_model_path models/multichoice_model.bin --vocab_path models/google_zh_vocab.txt \
>                                   --test_path datasets/c3/test.json \
>                                   --prediction_path datasets/c3/prediction.json --max_choices_num 4 \
>                                   --embedding word_pos_seg --encoder transformer --mask fully_visible
> ```

1. 参数choice存在限制：run_c3.py: error: argument --embedding: invalid choice: 'word_pos_seg' (choose from 'bert', 'word')
2. 删除choice限制后，显示无mask参数：run_c3.py: error: unrecognized arguments: --mask fully_visible
3. 添加mask参数后，报错：
Traceback (most recent call last):
File "UER-py-master/run_c3.py", line 250, in
main()
File "UER-py-master/run_c3.py", line 181, in main
model = MultipleChoice(args)
File "UER-py-master/run_c3.py", line 24, in init
self.embedding = globals()[args.embedding.capitalize() + "Embedding"](args, len(args.tokenizer.vocab))
KeyError: 'Word_pos_segEmbedding'

**Comment by P01son6415** [comment]
已经更新 run_c3.py 相关参数设置，请重新 clone 最新的代码再尝试一次。感谢你发现的这个问题！
