### ISSUE TITLE
Bug report: run_c3.py

### ISSUE THREAD

**Issue by Judenpech** [dbiir/UER-py#95]
在代码段中：

```
def read_dataset(args, path):
   ...

    dataset = []
    for i, example in enumerate(examples):
        tgt = 0
        for k in range(args.max_choices_num):
            if example[2 + k] == example[6]:
                tgt = k
        dataset.append(([], tgt, []))
    ...
```

`if example[2 + k] == example[6]:`无法应对`args.max_choices_num`不为4的情况。应该改成`if example[2 + k] == example[-1]:`。

**Comment by P01son6415** [comment]
run_c3 中的 read_dataset 函数是针对 C3 数据集的， C3 数据集中 max_choices_num 是严格为 4 。
由于阅读理解数据集的格式各不相同，因此我们建议在用户使用其他数据集时重写 read_dataset 函数。
