### ISSUE TITLE
想完成“一对短语是否意思相同”这样的二分类，不知道怎样的方案好？

### ISSUE THREAD

**Issue by srhouyu** [dbiir/UER-py#97]
如果是对单个句子进行监督的二分类训练，那还是比较容易理解的。但是，我现在要分类的是“一对句子之间是否意思相同”。
感觉好像可以把两个句子拼合成一个句子，然后对这个合成句子进行二分类。但是，我不确定怎样的拼合方法是模型所能支持的。
我是否可以简单地用分号把两个短语连成一个句子，然后就这么标注？
label | text
------------ | -------------
0 | 张三的高端电脑；张三的低端电脑
0 | 张三的高端电脑；张八的高端电脑
1 | 张三的高端电脑；张三的高端的电脑
1 | 张三的高端电脑；张三的高端计算机

标签0表示“意思不同”，即关键信息有区别
标签1表示“意思相同”，即关键信息没有区别
  
另外，还搜索到叫句子嵌入（Sentence Embedding）这类无监督方法，不知道二者进行句子嵌入再比较相似度是否可行？这方面UER是否有可以用的组件？

**Comment by zhezhaoa** [comment]
您好，run_classifier.py支持文本对分类
数据集文件需要3列，label text_a text_b ，用\t分隔

具体可以参考 页面下的 https://github.com/dbiir/UER-py/wiki/%E4%B8%8B%E6%B8%B8%E4%BB%BB%E5%8A%A1%E5%BE%AE%E8%B0%83
run_classifier.py 文本对分类使用示例
其对lcqmc文本对分类数据集进行了分类
跑通lcqmc的例子，然后换成自己的数据集就可以了

**Comment by svjack** [comment]
> 如果是对单个句子进行监督的二分类训练，那还是比较容易理解的。但是，我现在要分类的是“一对句子之间是否意思相同”。
> 感觉好像可以把两个句子拼合成一个句子，然后对这个合成句子进行二分类。但是，我不确定怎样的拼合方法是模型所能支持的。
> 我是否可以简单地用分号把两个短语连成一个句子，然后就这么标注？
> label | text
> ------------ | -------------
> 0 | 张三的高端电脑；张三的低端电脑
> 0 | 张三的高端电脑；张八的高端电脑
> 1 | 张三的高端电脑；张三的高端的电脑
> 1 | 张三的高端电脑；张三的高端计算机
> 
> 标签0表示“意思不同”，即关键信息有区别
> 标签1表示“意思相同”，即关键信息没有区别
>   
> 另外，还搜索到叫句子嵌入（Sentence Embedding）这类无监督方法，不知道二者进行句子嵌入再比较相似度是否可行？这方面UER是否有可以用的组件？
试试这个？
https://www.sbert.net/examples/applications/cross-encoder/README.html

**Comment by svjack** [comment]
> 您好，run_classifier.py支持文本对分类
> 数据集文件需要3列，label text_a text_b ，用\t分隔
> 
> 具体可以参考 页面下的 https://github.com/dbiir/UER-py/wiki/%E4%B8%8B%E6%B8%B8%E4%BB%BB%E5%8A%A1%E5%BE%AE%E8%B0%83
> run_classifier.py 文本对分类使用示例
> 其对lcqmc文本对分类数据集进行了分类
> 跑通lcqmc的例子，然后换成自己的数据集就可以了

那是不是问答的精排，也可以用？

**Comment by srhouyu** [comment]
> 您好，run_classifier.py支持文本对分类
> 数据集文件需要3列，label text_a text_b ，用\t分隔
> 
> 具体可以参考 页面下的 https://github.com/dbiir/UER-py/wiki/%E4%B8%8B%E6%B8%B8%E4%BB%BB%E5%8A%A1%E5%BE%AE%E8%B0%83
> run_classifier.py 文本对分类使用示例
> 其对lcqmc文本对分类数据集进行了分类
> 跑通lcqmc的例子，然后换成自己的数据集就可以了

谢谢，这个恰好跟我的需求一样

**Comment by srhouyu** [comment]
> > 如果是对单个句子进行监督的二分类训练，那还是比较容易理解的。但是，我现在要分类的是“一对句子之间是否意思相同”。
> > 感觉好像可以把两个句子拼合成一个句子，然后对这个合成句子进行二分类。但是，我不确定怎样的拼合方法是模型所能支持的。
> > 我是否可以简单地用分号把两个短语连成一个句子，然后就这么标注？
> > 
> > 
> > 
> > label
> > text
> > 
> > 
> > 
> > 
> > 0
> > 张三的高端电脑；张三的低端电脑
> > 
> > 
> > 0
> > 张三的高端电脑；张八的高端电脑
> > 
> > 
> > 1
> > 张三的高端电脑；张三的高端的电脑
> > 
> > 
> > 1
> > 张三的高端电脑；张三的高端计算机
> > 
> > 
> > 
> > 标签0表示“意思不同”，即关键信息有区别
> > 标签1表示“意思相同”，即关键信息没有区别
> > 另外，还搜索到叫句子嵌入（Sentence Embedding）这类无监督方法，不知道二者进行句子嵌入再比较相似度是否可行？这方面UER是否有可以用的组件？
> > 试试这个？
> > https://www.sbert.net/examples/applications/cross-encoder/README.html

谢谢，我也考察一下这个

**Comment by svjack** [comment]
> > > 如果是对单个句子进行监督的二分类训练，那还是比较容易理解的。但是，我现在要分类的是“一对句子之间是否意思相同”。
> > > 感觉好像可以把两个句子拼合成一个句子，然后对这个合成句子进行二分类。但是，我不确定怎样的拼合方法是模型所能支持的。
> > > 我是否可以简单地用分号把两个短语连成一个句子，然后就这么标注？
> > > 
> > > 
> > > 
> > > label
> > > text
> > > 
> > > 
> > > 
> > > 
> > > 0
> > > 张三的高端电脑；张三的低端电脑
> > > 
> > > 
> > > 0
> > > 张三的高端电脑；张八的高端电脑
> > > 
> > > 
> > > 1
> > > 张三的高端电脑；张三的高端的电脑
> > > 
> > > 
> > > 1
> > > 张三的高端电脑；张三的高端计算机
> > > 
> > > 
> > > 
> > > 标签0表示“意思不同”，即关键信息有区别
> > > 标签1表示“意思相同”，即关键信息没有区别
> > > 另外，还搜索到叫句子嵌入（Sentence Embedding）这类无监督方法，不知道二者进行句子嵌入再比较相似度是否可行？这方面UER是否有可以用的组件？
> > > 试试这个？
> > > https://www.sbert.net/examples/applications/cross-encoder/README.html
> 
> 谢谢，我也考察一下这个

另外我想问一下 你在实际解决这类问题时，如果有左面的若干句子之间语义相近的问题时，模型会不会区分不出来？
如果就按你的例子，还有一个是“张三的高配服务器”，它与其它若干相似的句子组成正样本，而这些正样本与“张三的高端电脑“不想交,这时会不会出现模型识别不出的情况？
如何出现了如何做正样本合并比较好。
比如如何找到这些相似的合并成一组？

**Comment by svjack** [comment]
> 您好，run_classifier.py支持文本对分类
> 数据集文件需要3列，label text_a text_b ，用\t分隔
> 
> 具体可以参考 页面下的 https://github.com/dbiir/UER-py/wiki/%E4%B8%8B%E6%B8%B8%E4%BB%BB%E5%8A%A1%E5%BE%AE%E8%B0%83
> run_classifier.py 文本对分类使用示例
> 其对lcqmc文本对分类数据集进行了分类
> 跑通lcqmc的例子，然后换成自己的数据集就可以了

用run_dbqa.py是不是也行？

**Comment by srhouyu** [comment]
> > > > 如果是对单个句子进行监督的二分类训练，那还是比较容易理解的。但是，我现在要分类的是“一对句子之间是否意思相同”。
> > > > 感觉好像可以把两个句子拼合成一个句子，然后对这个合成句子进行二分类。但是，我不确定怎样的拼合方法是模型所能支持的。
> > > > 我是否可以简单地用分号把两个短语连成一个句子，然后就这么标注？
> > > > label
> > > > text
> > > > 0
> > > > 张三的高端电脑；张三的低端电脑
> > > > 0
> > > > 张三的高端电脑；张八的高端电脑
> > > > 1
> > > > 张三的高端电脑；张三的高端的电脑
> > > > 1
> > > > 张三的高端电脑；张三的高端计算机
> > > > 标签0表示“意思不同”，即关键信息有区别
> > > > 标签1表示“意思相同”，即关键信息没有区别
> > > > 另外，还搜索到叫句子嵌入（Sentence Embedding）这类无监督方法，不知道二者进行句子嵌入再比较相似度是否可行？这方面UER是否有可以用的组件？
> > > > 试试这个？
> > > > https://www.sbert.net/examples/applications/cross-encoder/README.html
> > 
> > 
> > 谢谢，我也考察一下这个
> 
> 另外我想问一下 你在实际解决这类问题时，如果有左面的若干句子之间语义相近的问题时，模型会不会区分不出来？
> 如果就按你的例子，还有一个是“张三的高配服务器”，它与其它若干相似的句子组成正样本，而这些正样本与“张三的高端电脑“不想交,这时会不会出现模型识别不出的情况？
> 如何出现了如何做正样本合并比较好。
> 比如如何找到这些相似的合并成一组？

我还没有开始标注，只是在考虑可行性，不清楚问题有多大。不过，肯定得加一些数据增强手段。

**Comment by zhezhaoa** [comment]
> > 您好，run_classifier.py支持文本对分类
> > 数据集文件需要3列，label text_a text_b ，用\t分隔
> > 具体可以参考 页面下的 https://github.com/dbiir/UER-py/wiki/%E4%B8%8B%E6%B8%B8%E4%BB%BB%E5%8A%A1%E5%BE%AE%E8%B0%83
> > run_classifier.py 文本对分类使用示例
> > 其对lcqmc文本对分类数据集进行了分类
> > 跑通lcqmc的例子，然后换成自己的数据集就可以了
> 
> 用run_dbqa.py是不是也行？

您好是的哈
run_dbqa大部分代码重用了run_classifier的代码，只不过多了一个group的概念，一个text_a对应多个text_b，我们从多个text_b中选择一个最合适的进行配对

**Comment by zhezhaoa** [comment]
> 如果是对单个句子进行监督的二分类训练，那还是比较容易理解的。但是，我现在要分类的是“一对句子之间是否意思相同”。
> 感觉好像可以把两个句子拼合成一个句子，然后对这个合成句子进行二分类。但是，我不确定怎样的拼合方法是模型所能支持的。
> 我是否可以简单地用分号把两个短语连成一个句子，然后就这么标注？
> 
> label	text
> 0	张三的高端电脑；张三的低端电脑
> 0	张三的高端电脑；张八的高端电脑
> 1	张三的高端电脑；张三的高端的电脑
> 1	张三的高端电脑；张三的高端计算机
> 标签0表示“意思不同”，即关键信息有区别
> 标签1表示“意思相同”，即关键信息没有区别
> 
> 另外，还搜索到叫句子嵌入（Sentence Embedding）这类无监督方法，不知道二者进行句子嵌入再比较相似度是否可行？这方面UER是否有可以用的组件？

可以通过scripts/extract_features.py抽取特征，然后进行余弦相似度的计算
我们很快会在上面加上BERT-whitening这个方法，效果会有比较大的提升
https://spaces.ac.cn/archives/8069
